# Generated by Django 5.1.3 on 2024-11-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelaje', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadecision',
            name='related_areas',
            field=models.ManyToManyField(blank=True, to='modelaje.areadecision'),
        ),
    ]
