# Generated by Django 5.1.3 on 2024-11-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelaje', '0002_areadecision_related_areas'),
    ]

    operations = [
        migrations.AddField(
            model_name='areadecision',
            name='is_important',
            field=models.BooleanField(default=False),
        ),
    ]
