# Generated by Django 5.1.3 on 2024-12-04 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelaje', '0003_areadecision_is_important'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('area_decision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelaje.areadecision')),
            ],
        ),
    ]
