# Generated by Django 5.1.3 on 2024-12-08 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelaje', '0004_opciondecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaComparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=7, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('order', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='opciondecision',
            name='area_decision',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciondecision_set', to='modelaje.areadecision'),
        ),
    ]
