# Generated by Django 5.1.3 on 2024-12-15 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelaje', '0005_areacomparacion_alter_opciondecision_area_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomparacion',
            name='peso',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='DecisionAlternative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hexa', models.CharField(max_length=7, unique=True)),
                ('options', models.ManyToManyField(related_name='alternatives', to='modelaje.opciondecision')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionComparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveIntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=0)),
                ('area_comparacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelaje.areacomparacion')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelaje.opciondecision')),
            ],
            options={
                'unique_together': {('option', 'area_comparacion')},
            },
        ),
    ]
