# Generated by Django 5.1.3 on 2024-12-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modelaje', '0007_areacomparacion_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomparacion',
            name='min_value',
            field=models.IntegerField(default=0),
        ),
    ]
